namespace Process.Domain.Entities
{
    public class Citizen
    {
        public long CitizenId { get; set; }
        public Guid CitizenGuid { get; set; }
        public long? AgreementId { get; set; }
        public int? DocumentTypeId { get; set; }
        public string? DocumentNumber { get; set; }
        public string? Email { get; set; }
        public int? CountryId { get; set; }
        public string? Phone { get; set; }
        public string? FirstName { get; set; }
        public string? SecondName { get; set; }
        public string? LastName { get; set; }
        public string? SecondLastName { get; set; }
        public bool? Alive { get; set; }
        public int? DocumentStatus { get; set; }
        public DateTime? DocumentIssueDate { get; set; }
        public DateTime? BirthDate { get; set; }
        public string? Location { get; set; }
        public long? AdviserId { get; set; }
        public long? BranchId { get; set; }
        public bool? Status { get; set; }
        public bool AutoGeneratedValidation { get; set; }
        public float? QualificationProcesses { get; set; }
        public string? ResolutionNumber { get; set; }
        public string? Particle { get; set; }
        public string? IssueDepartment { get; set; }
        public Guid? AccountId { get; set; }
        public DateTime? CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public bool? Active { get; set; }
        public bool? IsDeleted { get; set; }
    }
}
