apiVersion: apps/v1
kind: Deployment
metadata:
  name: drawflowprocess
  namespace: pre-microservice
spec:
  replicas: 5
  selector:
    matchLabels:
      app: drawflowprocess
  template:
    metadata:
      labels:
        app: drawflowprocess
    spec:
      nodeSelector:
        kubernetes.io/os: linux
        kubernetes.io/arch: amd64
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - drawflowprocess
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: drawflowprocess
          image: #{ACR_NAME}#.azurecr.io/nextgenid.api.drawflowprocess:v.#{Build.BuildId}#
          resources:
              requests:
                cpu: 25m
                memory: 192Mi
                ephemeral-storage: 2000Mi
              limits:
                cpu: 300m
                memory: 500Mi
                ephemeral-storage: 5000Mi
          ports:
            - containerPort: 7240
          envFrom:
            - configMapRef:
                name: drawflowprocess-config
          env:
            - name: ASPNETCORE_URLS
              value: http://+:7240
            - name: TARGET_PLATFORMS
              value: linux/amd64,linux/arm64
