apiVersion: v1
kind: ConfigMap
metadata:
  name: uitemplate-config
  namespace: pre-microservice
data:
  ConnectionStrings__MongoDb: mongodb://cdb-aeu-pre-nextgenid:I304I6JQZUpeNfCpMjqctbSnftCO0pe4UxPvswlOECINMhINpkjFbImvThPP9wTEC4CmNScWwLAWACDb2ceHhg==@cdb-aeu-pre-nextgenid.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@cdb-aeu-pre-nextgenid@ 
  ApiCentralLog__UrlBase: "http://10.161.196.100/apireceivelogs/"
  ApiCentralLog__Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQcm9kdWN0SUQiOiI1IiwiZXhwIjoxODYwMTYwMDU0LCJpc3MiOiJNaUxvZ3MiLCJhdWQiOiJPbGltcGlhSVQifQ.g8V4W_mSQafmkoqMOBKiNr-nX_v6-_o_cNTmQog_JSQ 
  ConnectionStrings__AzureBlobStorage: DefaultEndpointsProtocol=https;AccountName=sacaeuprenextgenid;AccountKey=61wJ+s+JG5AHfLV972nnMdeNrTI5Zi7X5OEIUXwjxfgKv1e3Pcpvursg7kcQ4UKyXao177iK8KiO+AStz8aOyQ==;EndpointSuffix=core.windows.net 
  KeyVault__ConnectionKeyVault: "false"

