apiVersion: v1
kind: ConfigMap
metadata:
  name: apigateway-config
  namespace: pre-microservice
data:
  OpenIddict__Base: "https://okeystudiopre.olimpiait.com/"
  ApiCentralLog__UrlBase: "http://10.163.196.100/apireceivelogs/"
  ApiCentralLog__Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQcm9kdWN0SUQiOiIyIiwiZXhwIjoxODQxMTUwMzk3LCJpc3MiOiJNaUxvZ3MiLCJhdWQiOiJPbGltcGlhSVQifQ.91JVDx437TefA-jLtYF21gnMmD0iC4e_xzifEJN5pa0
  ConnectionStrings__AzureBlobStorage: DefaultEndpointsProtocol=https;AccountName=sacaeudevnextgenid;AccountKey=eRb3JE/ghTUC5c3t3a8HgfcAcSIK6olLMBWrgUN5xcqNODk+n4s25ipIcKJnq5v7w+M9M7ESvlHT+AStgBlDMg==;EndpointSuffix=core.windows.net 
  AllowedOrigins__0: "https://okeystudiopre.olimpiait.com"
  AllowedOrigins__1: "http://localhost:4200"
  AllowedOrigins__2: "https://nonvitalized-fishily-stanton.ngrok-free.dev"
  AllowedOrigins__3: "https://unmethodic-jude-castlelike.ngrok-free.dev"
  KeyVault__ConnectionKeyVault: "false"
  RECONOSERID_LOGS_HOST: "transversales-pre-apitrazabilidad.olimpiait.com"
  RECONOSERID_LOGS_PORT: "443"
  Trazabilidad__Usuario: "Usu_tracePre"
  Trazabilidad__Contrasena: "81HkE}N%34Hm"
  Trazabilidad__Codigo: "5b4ea07f-4d1c-405e-99b3-5722a09e010c"
  ConnectionStrings__OKeyConnection: Server=tcp:sdbaeudevnextgenid.database.windows.net,1433;Initial Catalog=dbs-aeu-dev-okeystudio;Persist Security Info=False;User ID=usrdbokeyqa;Password=Usrdb0k3ys4ndb0x;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30; 

