apiVersion: v1
kind: ConfigMap
metadata:
  name: dactyloscopy-config
  namespace: pre-microservice
data:
  ConnectionStrings__DefaultConnection: Server=tcp:sdbaeudevnextgenid.database.windows.net,1433;Initial Catalog=dbs-aeu-dev-okeystudio;Persist Security Info=False;User ID=usrdbokeyqa;Password=Usrdb0k3ys4ndb0x;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30; 
  ApiCentralLog__UrlBase: "http://10.163.196.100/apireceivelogs/"
  ApiCentralLog__Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQcm9kdWN0SUQiOiIyIiwiZXhwIjoxODQxMTUwMzk3LCJpc3MiOiJNaUxvZ3MiLCJhdWQiOiJPbGltcGlhSVQifQ.91JVDx437TefA-jLtYF21gnMmD0iC4e_xzifEJN5pa0 
  ConnectionStrings__AzureBlobStorage: DefaultEndpointsProtocol=https;AccountName=sacaeudevnextgenid;AccountKey=eRb3JE/ghTUC5c3t3a8HgfcAcSIK6olLMBWrgUN5xcqNODk+n4s25ipIcKJnq5v7w+M9M7ESvlHT+AStgBlDMg==;EndpointSuffix=core.windows.net
  ExternalApi__BaseUrlDactyloscopy: "https://recidampre.olimpiait.com:8301"
  KeyVault__ConnectionKeyVault: "false"
  

