apiVersion: v1
kind: ConfigMap
metadata:
  name: process-config
  namespace: pre-microservice
data: 
  ConnectionStrings__OKeyConnection: Server=tcp:sdbaeudevnextgenid.database.windows.net,1433;Initial Catalog=dbs-aeu-dev-okeystudio;Persist Security Info=False;User ID=usrdbokeyqa;Password=Usrdb0k3ys4ndb0x;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30; 
  ApiCentralLog__UrlBase: "http://10.163.196.100/apireceivelogs/"
  ExternalApi__BaseUrlAdtp: "http://10.163.200.102/apicore"
  ExternalApi__TokenAdtp: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQcm9kdWN0SUQiOiIyNSIsImV4cCI6MTg2NDE1OTgyMSwiaXNzIjoiTWlBVERQIiwiYXVkIjoiT2xpbXBpYUlUIn0.OWqKn6LiZ8c7cMxLGiFIxZG_pPRFUnh4zxOn02uG1ZI
  ApiCentralLog__Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJQcm9kdWN0SUQiOiIyIiwiZXhwIjoxODQxMTUwMzk3LCJpc3MiOiJNaUxvZ3MiLCJhdWQiOiJPbGltcGlhSVQifQ.91JVDx437TefA-jLtYF21gnMmD0iC4e_xzifEJN5pa0
  ExternalApi__BaseUrlSso: "https://okeystudiopre.olimpiait.com/"
  ExternalApi__BaseUrlReconoser1: "https://recidampre.olimpiait.com:8301"
  ExternalApi__BaseUrlReconoser2: "https://recidampre.olimpiait.com:8304"
  ExternalApi__BaseUrlVeriFace: "https://10.161.64.4:3412"
  RedirectValidationUrl: "https://okeypre.olimpiait.com/webflow/#/redirect"
  ApiClient: Angular
  ApiKey: 5UebhcVqdiSGeMqW431DF
  ApiKeyVeriFace: JbLuuHA4yMYWseYfiekHKz5nDIDtYFLORob5Ffale8o
  RecaptchaSecret: 6Lez8UwsAAAAAH9FarTD4gC7na4R1vUSVrKJOp5b
  ConnectionStrings__AzureBlobStorage: DefaultEndpointsProtocol=https;AccountName=sacaeudevnextgenid;AccountKey=eRb3JE/ghTUC5c3t3a8HgfcAcSIK6olLMBWrgUN5xcqNODk+n4s25ipIcKJnq5v7w+M9M7ESvlHT+AStgBlDMg==;EndpointSuffix=core.windows.net 
  KeyVault__ConnectionKeyVault: "false"
  WhatsappService__CodeWhatsapp: "a2342e53-9360-40c1-98c9-067f71f595cb"
  WhatsappService__UserWhatsapp: "usu_OkeyDev"
  WhatsappService__PasswordWhatsapp: "{7B300,fvd&D"
  ExternalApi__BaseUrlWhatsapp: "https://okeyapiwhatsappdev.olimpiait.com"
  AllowKeys: "true"
  AllowEncryptBlob: "false"

