apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: pre-microservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7206
      targetPort: 7206
  selector:
    app: apigateway