apiVersion: v1
kind: Service
metadata:
  name: dactyloscopy
  namespace: pre-microservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7236
      targetPort: 7236
  selector:
    app: dactyloscopy