apiVersion: v1
kind: Service
metadata:
  name: digitalsignature
  namespace: pre-microservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7298
      targetPort: 7298
  selector:
    app: digitalsignature