apiVersion: v1
kind: Service
metadata:
  name: drawflowprocess
  namespace: pre-microservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7240
      targetPort: 7240
  selector:
    app: drawflowprocess