apiVersion: v1
kind: Service
metadata:
  name: drawflowconfiguration
  namespace: pre-microservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7250
      targetPort: 7250
  selector:
    app: drawflowconfiguration