apiVersion: v1
kind: Service
metadata:
  name: process
  namespace: pre-microservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7292
      targetPort: 7292
  selector:
    app: process