apiVersion: v1
kind: Service
metadata:
  name: uiconfiguration
  namespace: pre-microservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7264
      targetPort: 7264
  selector:
    app: uiconfiguration