apiVersion: v1
kind: Service
metadata:
  name: uitemplate
  namespace: pre-microservice
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7288
      targetPort: 7288
  selector:
    app: uitemplate