// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Process.Infrastructure.Data;

#nullable disable

namespace Process.Infrastructure.Migrations
{
    [DbContext(typeof(ContextSqlServerDB))]
    [Migration("20251110185842_UPDATE_COUNTRY_COLUMN_FRECUENT_COUNTRY")]
    partial class UPDATE_COUNTRY_COLUMN_FRECUENT_COUNTRY
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
