// <auto-generated />
using DrawFlowConfiguration.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrawFlowConfiguration.Infrastructure.Migrations
{
    [DbContext(typeof(ContextSqlServerDB))]
    [Migration("20260206200001_V2_CREATE_PROCEDURE_SP_PURGE_OLD_WORKFLOWS")]
    partial class V2_CREATE_PROCEDURE_SP_PURGE_OLD_WORKFLOWS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
