// <auto-generated />
using DrawFlowConfiguration.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrawFlowConfiguration.Infrastructure.Migrations
{
    [DbContext(typeof(ContextSqlServerDB))]
    [Migration("20260324150449_UPDATE_INACTIVAR_DOCUMENTOS_NO_UTILIZADOS_X_PAIS")]
    partial class UPDATE_INACTIVAR_DOCUMENTOS_NO_UTILIZADOS_X_PAIS
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
