// <auto-generated />
using DrawFlowConfiguration.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrawFlowConfiguration.Infrastructure.Migrations
{
    [DbContext(typeof(ContextSqlServerDB))]
    [Migration("20260409213625_EDIT-DATA-UNIFICAR-PASAPORTES-DOCTYPE")]
    partial class EDITDATAUNIFICARPASAPORTESDOCTYPE
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
