using Dapper;
using Process.Domain.Entities;
using Process.Domain.Repositories;
using Process.Infrastructure.Data;
using System.Data;
using static Domain.Enums.Enumerations;

namespace Process.Infrastructure.Repositories
{
    public class CitizenRepository(
        SQLServerConnectionFactory connectionFactory
    ) : ICitizenRepository
    {
        private readonly SQLServerConnectionFactory _factory = connectionFactory;

        public async Task<Citizen?> GetCitizenByDocumentNumberAndAgreementIdAsync(
            string documentNumber,
            long agreementId
        )
        {
            string sql = @"
                SELECT 
                    [CitizenId],[CitizenGuid],[AgreementId],[DocumentTypeId],[DocumentNumber],[Email],
                    [CountryId],[Phone],[FirstName],[SecondName],[LastName],[SecondLastName],[Alive],
                    [DocumentStatus],[DocumentIssueDate],[BirthDate],[Location],[AdviserId],[BranchId],
                    [Status],[AutoGeneratedValidation],[QualificationProcesses],
                    [ResolutionNumber],[Particle],[IssueDepartment],[AccountId],[CreatedDate],[UpdatedDate],[Active],[IsDeleted]
                FROM [dbo].[Citizen]
                WHERE DocumentNumber = @documentNumber AND AgreementId = @agreementId
            ";

            using var connection = CreateConnection();
            return await connection.QueryFirstOrDefaultAsync<Citizen>(sql, new { documentNumber, agreementId });
        }

        public async Task<Citizen?> GetCitizenByGuidAsync(Guid citizenGuid)
        {
            string sql = @"
                SELECT 
                    [CitizenId],[CitizenGuid],[AgreementId],[DocumentTypeId],[DocumentNumber],[Email],
                    [CountryId],[Phone],[FirstName],[SecondName],[LastName],[SecondLastName],[Alive],
                    [DocumentStatus],[DocumentIssueDate],[BirthDate],[Location],[AdviserId],[BranchId],
                    [Status],[AutoGeneratedValidation],[QualificationProcesses],
                    [ResolutionNumber],[Particle],[IssueDepartment],[AccountId],[CreatedDate],[UpdatedDate],[Active],[IsDeleted]
                FROM [dbo].[Citizen]
                WHERE CitizenGuid = @citizenGuid
            ";

            using var connection = CreateConnection();
            return await connection.QueryFirstOrDefaultAsync<Citizen>(sql, new { citizenGuid });
        }

        public async Task<Citizen> SaveCitizenAsync(Citizen citizen)
        {
            string sqlCommand = @"
                INSERT INTO [dbo].[Citizen](
                    [CitizenGuid],[AgreementId],[DocumentTypeId],[DocumentNumber],[Email],[CountryId],[Phone],[FirstName],[SecondName],[LastName],
                    [SecondLastName],[Alive],[DocumentStatus],[DocumentIssueDate],[BirthDate],[Location],[AdviserId],[BranchId],[Status],[AutoGeneratedValidation],
                    [QualificationProcesses],[ResolutionNumber],[Particle],[IssueDepartment],[AccountId],[CreatedDate],[UpdatedDate],[Active],[IsDeleted]
                )
                OUTPUT INSERTED.*
                VALUES(
                    @CitizenGuid,@AgreementId,@DocumentTypeId,@DocumentNumber,@Email,@CountryId,@Phone,@FirstName,@SecondName,@LastName,
                    @SecondLastName,@Alive,@DocumentStatus,@DocumentIssueDate,@BirthDate,@Location,@AdviserId,@BranchId,@Status,@AutoGeneratedValidation,
                    @QualificationProcesses,@ResolutionNumber,@Particle,@IssueDepartment,@AccountId,@CreatedDate,@UpdatedDate,@Active,@IsDeleted
                )
            ";

            using var connection = CreateConnection();
            return await connection.QuerySingleAsync<Citizen>(sqlCommand, citizen);
        }

        public async Task<Citizen> UpdateCitizenAsync(Citizen citizen)
        {
            string sqlCommand = @"
                UPDATE [dbo].[Citizen]
                SET
                   [CitizenGuid] = @CitizenGuid
                  ,[AgreementId] = @AgreementId
                  ,[DocumentTypeId] = @DocumentTypeId
                  ,[DocumentNumber] = @DocumentNumber
                  ,[Email] = @Email
                  ,[CountryId] = @CountryId
                  ,[Phone] = @Phone
                  ,[FirstName] = @FirstName
                  ,[SecondName] = @SecondName
                  ,[LastName] = @LastName
                  ,[SecondLastName] = @SecondLastName
                  ,[Alive] = @Alive
                  ,[DocumentStatus] = @DocumentStatus
                  ,[DocumentIssueDate] = @DocumentIssueDate
                  ,[BirthDate] = @BirthDate
                  ,[Location] = @Location
                  ,[AdviserId] = @AdviserId
                  ,[BranchId] = @BranchId
                  ,[Status] = @Status
                  ,[AutoGeneratedValidation] = @AutoGeneratedValidation
                  ,[QualificationProcesses] = @QualificationProcesses
                  ,[ResolutionNumber] = @ResolutionNumber
                  ,[Particle] = @Particle
                  ,[IssueDepartment] = @IssueDepartment
                  ,[AccountId] = @AccountId
                  ,[CreatedDate] = @CreatedDate
                  ,[UpdatedDate] = @UpdatedDate
                  ,[Active] = @Active
                  ,[IsDeleted] = @IsDeleted
                OUTPUT INSERTED.*
                WHERE [CitizenId] = @citizenId
            ";

            using var connection = CreateConnection();
            return await connection.QuerySingleAsync<Citizen>(sqlCommand, citizen);
        }

        private IDbConnection CreateConnection()
        {
            return _factory.CreateConnection(ConnectionsName.OKeyConnection);
        }
    }
}
